### ISSUE TITLE
Support update operators other than $set

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/module-ballerinax-mongodb#76]
**Description:**
Following MongoDB update operations are not supported such as $inc, $push, $addToSet

These can be supported by introducing new record for the 
```ballerina
public type UpdateCondition record {
    map<json>? set = ();
    map<json>? inc = ();
    map<json>? push = ();
    map<json>? addToSet = ();
};
public remote function update(UpdateCondition updateCondition, map<json>? filter = (), boolean isMultiple = false, 
                                                                                                boolean upsert = false)
}

```
Above `set` will be UpdateCondition record used when multiple update conditions can be used.

**Comment by kasthuriraajan** [comment]
This is an improvement need to be done.

**Comment by abeykoon** [comment]
Moved to https://github.com/ballerina-platform/ballerina-extended-library/issues/59
