### ISSUE TITLE
Return a stream rather than JSON

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/module-ballerinax-mongodb#77]
**Description:**
Since MongoDB client returns an iterator when can attach that to ballerina streams and return rather than processing the result beforehand to make to JSON. This will reduce the processing step by half and improve performance.

**Comment by kasthuriraajan** [comment]
This is an improvement need to be done.

**Comment by abeykoon** [comment]
Moved to https://github.com/ballerina-platform/ballerina-extended-library/issues/57
