### ISSUE TITLE
MongoDB connector does not support find with skip

### ISSUE THREAD

**Issue by maheeka** [ballerina-platform/module-ballerinax-mongodb#97]
**Description:**
In order to support paginated results in a search, skip functionality must be supported.
Please see : https://docs.mongodb.com/manual/reference/method/cursor.skip/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
Swan Lake Alpha 5

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by kasthuriraajan** [comment]
This is an improvement.

**Comment by abeykoon** [comment]
moved to https://github.com/ballerina-platform/ballerina-extended-library/issues/58
